# Nixpacks configuration for Frontend
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmd = "npm ci"

[phases.build]  
cmd = "npm run build"

[phases.start]
cmd = "npm start"