# Nixpacks configuration for Backend  
providers = ["python"]

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"